"""Provide functions shared among the codegen."""
import os
import pathlib

from aas_core_codegen.common import Stripped

_REPO_DIR = pathlib.Path(os.path.realpath(__file__)).parent.parent.parent


def generate_warning(
        path: str
) -> Stripped:
    """Generate the warning at the beginning of the module."""
    relative_path = pathlib.Path(path).relative_to(_REPO_DIR)

    return Stripped(
        f"""\
# Automatically generated by {str(relative_path)}.
# Do NOT edit or append!"""
    )
